Download dependencies if they are not found. This behavior can be changed with the use of --no-web. Dependencies found are downloaded to Clean/arch.

diff --git a/bin/ChrootCompile b/bin/ChrootCompile
--- a/bin/ChrootCompile
+++ b/bin/ChrootCompile
@@ -22,6 +22,7 @@ Add_Option_Entry "X" "cross-compile" "Use a cross-compiler according to the conf
 Add_Option_Entry "d" "use-directory" "Use specified directory as root for ChrootCompile." ""
 Add_Option_Boolean "S" "no-sign" "Do not try to sign the resulting package."
 Add_Option_Boolean "D" "no-debug" "Do not invoke bash if compilation fails."
+Add_Option_Boolean "W" "no-web" "Do not download precompiled packages from the web when Dependencies are not found." ""
 scriptExample="--local-repository /Files/Compile/LocalRecipes/Foo/1.0"
 helpOnNoArguments=yes
 Parse_Options "$@"
@@ -57,9 +58,10 @@ then
 fi
 
 unset nodebug
-if Boolean "no-debug"
-then nodebug=yes
-fi
+Boolean "no-debug" && nodebug=yes
+
+unset noweb
+Boolean "no-web" && noweb=yes
 
 hostarch=`uname -m`
 case "$hostarch" in
@@ -451,6 +453,14 @@ function unpack_package() {
    echo "$packagemd5" > Unpacked/$arch/_Checksums/$dep
    echo "$unpacked"
 }
+   
+function download_dependency() {
+   local pkg=$(FindPackage -t official_package "$1")
+   [ "$pkg" ] && wget "$pkg" || return
+   mv "$(basename "$pkg")" "$putclean"
+   pkg=`ls $putclean/$dep--* 2> /dev/null || true`
+   echo "$pkg"
+}
 
 function load_dependency() {
    local dep="$1"
@@ -459,9 +469,13 @@ function load_dependency() {
    if [ "$local_programs" ]
    then
       unpacked="/Programs/$dep/Current/"
-      [ -d $unpacked ] || Die "Dependency $dep could not be found."
+      if [ ! -d $unpacked ]
+      then
+         Die "Dependency $dep could not be found."
+      fi
    else
       local pkg=`get_package_for "$dep" "$repositories"`
+      [ ! "$pkg" ] && pkg=`download_dependency "$dep"`
       [ ! "$pkg" ] && Die "Dependency $dep could not be found. You may need to get the package and put it at Clean/$arch."
       unpacked=`unpack_package "$pkg" "$dep" "$arch"`
    fi
